var annotated_dup =
[
    [ "Adafruit_BMP280", "class_adafruit___b_m_p280.html", "class_adafruit___b_m_p280" ],
    [ "Adafruit_BMP280_Pressure", "class_adafruit___b_m_p280___pressure.html", "class_adafruit___b_m_p280___pressure" ],
    [ "Adafruit_BMP280_Temp", "class_adafruit___b_m_p280___temp.html", "class_adafruit___b_m_p280___temp" ],
    [ "Adafruit_BusIO_Register", "class_adafruit___bus_i_o___register.html", "class_adafruit___bus_i_o___register" ],
    [ "Adafruit_BusIO_RegisterBits", "class_adafruit___bus_i_o___register_bits.html", "class_adafruit___bus_i_o___register_bits" ],
    [ "Adafruit_GPS", "class_adafruit___g_p_s.html", "class_adafruit___g_p_s" ],
    [ "Adafruit_I2CDevice", "class_adafruit___i2_c_device.html", "class_adafruit___i2_c_device" ],
    [ "Adafruit_INA219", "class_adafruit___i_n_a219.html", "class_adafruit___i_n_a219" ],
    [ "Adafruit_Sensor", "class_adafruit___sensor.html", "class_adafruit___sensor" ],
    [ "Adafruit_SPIDevice", "class_adafruit___s_p_i_device.html", "class_adafruit___s_p_i_device" ],
    [ "bmp280_calib_data", "structbmp280__calib__data.html", "structbmp280__calib__data" ],
    [ "nmea_datavalue_t", "structnmea__datavalue__t.html", "structnmea__datavalue__t" ],
    [ "nmea_history_t", "structnmea__history__t.html", "structnmea__history__t" ],
    [ "Payload", "struct_payload.html", "struct_payload" ],
    [ "RawDegrees", "struct_raw_degrees.html", "struct_raw_degrees" ],
    [ "sensor_t", "structsensor__t.html", "structsensor__t" ],
    [ "sensors_color_t", "structsensors__color__t.html", "structsensors__color__t" ],
    [ "sensors_event_t", "structsensors__event__t.html", "structsensors__event__t" ],
    [ "sensors_vec_t", "structsensors__vec__t.html", "structsensors__vec__t" ],
    [ "TinyGPSAltitude", "struct_tiny_g_p_s_altitude.html", "struct_tiny_g_p_s_altitude" ],
    [ "TinyGPSCourse", "struct_tiny_g_p_s_course.html", "struct_tiny_g_p_s_course" ],
    [ "TinyGPSCustom", "class_tiny_g_p_s_custom.html", "class_tiny_g_p_s_custom" ],
    [ "TinyGPSDate", "struct_tiny_g_p_s_date.html", "struct_tiny_g_p_s_date" ],
    [ "TinyGPSDecimal", "struct_tiny_g_p_s_decimal.html", "struct_tiny_g_p_s_decimal" ],
    [ "TinyGPSHDOP", "struct_tiny_g_p_s_h_d_o_p.html", "struct_tiny_g_p_s_h_d_o_p" ],
    [ "TinyGPSInteger", "struct_tiny_g_p_s_integer.html", "struct_tiny_g_p_s_integer" ],
    [ "TinyGPSLocation", "struct_tiny_g_p_s_location.html", "struct_tiny_g_p_s_location" ],
    [ "TinyGPSPlus", "class_tiny_g_p_s_plus.html", "class_tiny_g_p_s_plus" ],
    [ "TinyGPSSpeed", "struct_tiny_g_p_s_speed.html", "struct_tiny_g_p_s_speed" ],
    [ "TinyGPSTime", "struct_tiny_g_p_s_time.html", "struct_tiny_g_p_s_time" ]
];