; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[common]
platform = espressif32
board = seeed_xiao_esp32c3
framework = arduino
monitor_speed = 115200
build_flags = 
	-DARDUINO_USB_MODE=1
	-DARDUINO_USB_CDC_ON_BOOT=1
lib_deps = 
	nrf24/RF24 @ 1.4.10

[env:xiao_usb]
extends = common
upload_protocol = esptool
upload_port = /dev/cu.usbmodem31101
upload_speed = 921600
lib_deps = nrf24/RF24@1.4.10

[env:xiao_ota]
extends = common
upload_protocol = espota
upload_port = LDRC_RX.local
