name: PlatformIO build

on:
  pull_request:
    types: [opened, reopened]
    paths:
      - ".github/workflows/platformIO_build.yml"
      - "*Code/**"
  push:
    paths:
      - ".github/workflows/platformIO_build.yml"
      - "*Code/**"
  # release:
  #   types: [published, edited]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
        fail-fast: false

        matrix:
          aspect:
            - ReceiverCode
            - TransmitterCode
            - SensorHubT32

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install PlatformIO
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade platformio

      - name: build aspect of project
        run: |
          cd ${{ matrix.aspect }}
          pio run

      - name: Save artifact
        uses: actions/upload-artifact@v3
        with:
          name: "${{ matrix.aspect }}Binaries"
          path: ${{ matrix.aspect }}/.pio/build/*/firmware.*

      # - name: Upload Release assets
      #   if: github.event_name == 'release'
      #   uses: csexton/release-asset-action@master
      #   with:
      #     pattern: "${{ matrix.aspect }}Code/.pio/build/*/firmware.*"
      #     github-token: ${{ secrets.GITHUB_TOKEN }}
